import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>StarTaildwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <h1 className={styles.title}>
            Welcome to <a href="https://StarTaildwind.com">StarTaildwind</a>
         </h1>
          <Link href="/buttons">Buttons</Link>
          <Link href="/buttons">NavBar</Link>
          <Link href="/buttons">Footers</Link>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
